defmodule AshTypescript.RPC.Codegen do
  @moduledoc """
  Generates TypeScript code for interacting with Ash resources via RPC.
  """

  import AshTypescript.TS.Codegen
  import AshTypescript.Helpers

  def generate_typescript_types(otp_app, opts \\ []) do
    endpoint_process = Keyword.get(opts, :process_endpoint, "/rpc/run")
    endpoint_validate = Keyword.get(opts, :validate_endpoint, "/rpc/validate")

    resources_and_actions = get_resources_and_actions(otp_app)

    # Collect all resources from all domains
    resources =
      otp_app
      |> Ash.Info.domains()
      |> Enum.flat_map(&Ash.Domain.Info.resources/1)
      |> Enum.uniq()

    generate_full_typescript(
      resources,
      resources_and_actions,
      endpoint_process,
      endpoint_validate,
      otp_app
    )
  end

  defp get_resources_and_actions(otp_app) do
    otp_app
    |> Ash.Info.domains()
    |> Enum.flat_map(fn domain ->
      # Get RPC configuration from the domain
      rpc_config = AshTypescript.RPC.Info.rpc(domain)

      Enum.flat_map(rpc_config, fn %{resource: resource, rpc_actions: rpc_actions} ->
        Enum.map(rpc_actions, fn rpc_action ->
          action = Ash.Resource.Info.action(resource, rpc_action.action)
          {resource, action, rpc_action}
        end)
      end)
    end)
  end

  defp generate_full_typescript(
         resources,
         resources_and_actions,
         endpoint_process,
         endpoint_validate,
         otp_app
       ) do
    """
    // Generated by AshTypescript
    // Do not edit this file manually

    #{generate_type_aliases()}

    #{generate_resource_schemas(resources, otp_app)}

    #{generate_utility_types()}

    #{generate_helper_functions()}

    #{generate_rpc_functions(resources_and_actions, endpoint_process, endpoint_validate, otp_app, resources)}
    """
  end

  defp generate_utility_types do
    """
    // Utility Types
    type PickFields<T, K extends keyof T> = Pick<T, K>;

    type ExtractCalculatedFields<
      T extends Record<string, any>,
      CalcFields extends Record<string, any>
    > = {
      [K in keyof T & keyof CalcFields]: CalcFields[K];
    };

    type CalculatedFieldsResult<T, CalcFields> = T extends Record<string, any>
      ? ExtractCalculatedFields<T, CalcFields>
      : {};

    type InferResourceResult<
      Resource extends Record<string, any>,
      Config extends {
        fields?: (keyof Resource)[];
        calculatedFields?: Record<string, any>;
        aggregateFields?: Record<string, any>;
        load?: Record<string, any>;
      }
    > = (Config["fields"] extends (keyof Resource)[]
      ? PickFields<Resource, Config["fields"][number]>
      : Resource) &
      (Config["calculatedFields"] extends Record<string, any>
        ? CalculatedFieldsResult<Config["calculatedFields"], any>
        : {}) &
      (Config["aggregateFields"] extends Record<string, any>
        ? Config["aggregateFields"]
        : {}) &
      (Config["load"] extends Record<string, any>
        ? InferRelationshipsFromMap<Config["load"]>
        : {});

    type InferRelationshipsFromMap<LoadMap> = {
      [K in keyof LoadMap]: LoadMap[K] extends {
        fields?: any[];
        calculatedFields?: Record<string, any>;
        aggregateFields?: Record<string, any>;
        load?: Record<string, any>;
      }
        ? LoadMap[K] extends { __array: true }
          ? Array<
              InferResourceResult<
                any,
                {
                  fields: LoadMap[K]["fields"];
                  calculatedFields: LoadMap[K]["calculatedFields"];
                  aggregateFields: LoadMap[K]["aggregateFields"];
                  load: LoadMap[K]["load"];
                }
              >
            >
          : InferResourceResult<
              any,
              {
                fields: LoadMap[K]["fields"];
                calculatedFields: LoadMap[K]["calculatedFields"];
                aggregateFields: LoadMap[K]["aggregateFields"];
                load: LoadMap[K]["load"];
              }
            >
        : never;
    };

    type InferArrayRelationshipResult<
      RelationshipType,
      Config extends {
        fields?: any[];
        calculatedFields?: Record<string, any>;
        aggregateFields?: Record<string, any>;
        load?: Record<string, any>;
      }
    > = RelationshipType extends { __array: true; __resource: infer Resource }
      ? Array<
          InferResourceResult<
            Resource,
            {
              fields: Config["fields"];
              calculatedFields: Config["calculatedFields"];
              aggregateFields: Config["aggregateFields"];
              load: Config["load"];
            }
          >
        >
      : never;

    type CalculatedFieldsConfig<T> = {
      [K in keyof T]?: boolean;
    };

    type AggregateFieldsConfig<T> = {
      [K in keyof T]?: boolean;
    };

    type LoadConfig<T> = {
      [K in keyof T]?: T[K] extends { __array: true }
        ? ArrayRelationshipConfig<T[K]>
        : RelationshipConfig<T[K]>;
    };

    type RelationshipConfig<T> = T extends {
      __resource: infer Resource;
      fields?: any;
      calculatedFields?: any;
      aggregateFields?: any;
      load?: any;
    }
      ? {
          fields?: T["fields"];
          calculatedFields?: T["calculatedFields"];
          aggregateFields?: T["aggregateFields"];
          load?: T["load"];
        }
      : never;

    type ArrayRelationshipConfig<T> = T extends {
      __array: true;
      __resource: infer Resource;
      fields?: any;
      calculatedFields?: any;
      aggregateFields?: any;
      load?: any;
    }
      ? {
          fields?: T["fields"];
          calculatedFields?: T["calculatedFields"];
          aggregateFields?: T["aggregateFields"];
          load?: T["load"];
        }
      : never;
    """
  end

  defp generate_rpc_functions(
         resources_and_actions,
         endpoint_process,
         endpoint_validate,
         otp_app,
         resources
       ) do
    # Generate relationship types for all resources
    relationship_types =
      resources
      |> Enum.map(&generate_relationship_types(&1, otp_app))
      |> Enum.join("\n\n")

    # Generate functions for each RPC action
    rpc_functions =
      resources_and_actions
      |> Enum.map(
        &generate_rpc_function(
          &1,
          resources_and_actions,
          endpoint_process,
          endpoint_validate,
          otp_app
        )
      )
      |> Enum.join("\n\n")

    """
    #{relationship_types}

    #{rpc_functions}
    """
  end

  defp generate_relationship_types(resource, _otp_app) do
    resource_name = resource |> Module.split() |> List.last()

    # Generate single relationship type
    single_rel = """
    type #{resource_name}Relationship = {
      __resource: #{resource_name}AttributesSchema;
      fields?: (keyof #{resource_name}AttributesSchema)[];
      calculatedFields?: CalculatedFieldsConfig<#{resource_name}CalculatedFieldsSchema>;
      aggregateFields?: AggregateFieldsConfig<#{resource_name}AggregateFieldsSchema>;
      load?: LoadConfig<#{resource_name}RelationshipSchema>;
    };
    """

    # Generate array relationship type
    array_rel = """
    type #{resource_name}ArrayRelationship = {
      __array: true;
      __resource: #{resource_name}AttributesSchema;
      fields?: (keyof #{resource_name}AttributesSchema)[];
      calculatedFields?: CalculatedFieldsConfig<#{resource_name}CalculatedFieldsSchema>;
      aggregateFields?: AggregateFieldsConfig<#{resource_name}AggregateFieldsSchema>;
      load?: LoadConfig<#{resource_name}RelationshipSchema>;
    };
    """

    """
    #{single_rel}

    #{array_rel}
    """
  end

  defp generate_rpc_function(
         {resource, action, rpc_action},
         _resources_and_actions,
         endpoint_process,
         _endpoint_validate,
         _otp_app
       ) do
    # Convert RPC action name to camelCase function name (e.g., read_todo -> readTodos)
    rpc_action_name = to_string(rpc_action.name)

    # Generate config type
    config_type = generate_config_type(resource, action, rpc_action_name)

    # Generate result inference type
    result_type = generate_result_type(resource, action, rpc_action_name)

    # Generate payload builder
    payload_builder = generate_payload_builder(rpc_action, action, rpc_action_name)

    # Generate RPC function
    rpc_function =
      generate_rpc_execution_function(rpc_action, action, rpc_action_name, endpoint_process)

    """
    #{config_type}

    #{result_type}

    #{payload_builder}

    #{rpc_function}
    """
  end

  defp generate_config_type(resource, action, rpc_action_name) do
    resource_name = resource |> Module.split() |> List.last()
    _function_name = snake_to_camel_case(rpc_action_name)
    config_name = "#{snake_to_pascal_case(rpc_action_name)}Config"

    # Base config fields
    base_fields = [
      "  fields?: (keyof #{resource_name}AttributesSchema)[];",
      "  calculatedFields?: CalculatedFieldsConfig<#{resource_name}CalculatedFieldsSchema>;",
      "  aggregateFields?: AggregateFieldsConfig<#{resource_name}AggregateFieldsSchema>;",
      "  load?: LoadConfig<#{resource_name}RelationshipSchema>;"
    ]

    # Add input fields based on action type
    input_fields =
      case action.type do
        :read ->
          filters =
            if action.arguments != [] do
              ["  filters?: {"] ++
                Enum.map(action.arguments, fn arg ->
                  "    #{arg.name}?: #{ash_type_to_typescript(arg.type)};"
                end) ++
                ["  };"]
            else
              []
            end

          pagination = [
            "  pagination?: {",
            "    limit?: number;",
            "    offset?: number;",
            "  };"
          ]

          filters ++ pagination

        :create ->
          accepts = Ash.Resource.Info.action(resource, action.name).accept || []
          arguments = action.arguments

          input_fields =
            if accepts != [] || arguments != [] do
              ["  input: {"] ++
                Enum.map(accepts, fn field_name ->
                  attr = Ash.Resource.Info.attribute(resource, field_name)
                  optional = attr.allow_nil? || attr.default != nil
                  base_type = ash_type_to_typescript(attr.type)
                  field_type = if attr.allow_nil?, do: "#{base_type} | null", else: base_type

                  "    #{field_name}#{if optional, do: "?", else: ""}: #{field_type};"
                end) ++
                Enum.map(arguments, fn arg ->
                  optional = arg.allow_nil? || arg.default != nil

                  "    #{arg.name}#{if optional, do: "?", else: ""}: #{ash_type_to_typescript(arg.type)};"
                end) ++
                ["  };"]
            else
              []
            end

          input_fields

        :update ->
          accepts = Ash.Resource.Info.action(resource, action.name).accept || []
          arguments = action.arguments

          id_field = ["  id: UUID;"]

          input_fields =
            if accepts != [] || arguments != [] do
              ["  input: {"] ++
                Enum.map(accepts, fn field_name ->
                  attr = Ash.Resource.Info.attribute(resource, field_name)

                  if attr.allow_nil? do
                    "    #{field_name}?: #{get_ts_type(attr)} | null;"
                  else
                    "    #{field_name}: #{get_ts_type(attr)};"
                  end
                end) ++
                Enum.map(arguments, fn arg ->
                  optional = arg.allow_nil? || arg.default != nil

                  "    #{arg.name}#{if optional, do: "?", else: ""}: #{ash_type_to_typescript(arg.type)};"
                end) ++
                ["  };"]
            else
              []
            end

          id_field ++ input_fields

        :destroy ->
          ["  id: UUID;"]

        action_type when action_type in [:action, :generic] ->
          arguments = action.arguments

          if arguments != [] do
            ["  input: {"] ++
              Enum.map(arguments, fn arg ->
                optional = arg.allow_nil? || arg.default != nil

                "    #{arg.name}#{if optional, do: "?", else: ""}: #{ash_type_to_typescript(arg.type)};"
              end) ++
              ["  };"]
          else
            []
          end
      end

    all_fields = input_fields ++ base_fields

    """
    type #{config_name} = {
    #{Enum.join(all_fields, "\n")}
    };
    """
  end

  defp generate_result_type(resource, action, rpc_action_name) do
    resource_name = resource |> Module.split() |> List.last()
    _function_name = snake_to_camel_case(rpc_action_name)

    rpc_action_name_pascal = snake_to_pascal_case(rpc_action_name)

    case action.type do
      :read when action.get? ->
        """
        type Infer#{rpc_action_name_pascal}Result<Config extends #{rpc_action_name_pascal}Config> =
          InferResourceResult<#{resource_name}AttributesSchema, Config> | null;
        """

      :read ->
        """
        type Infer#{rpc_action_name_pascal}Result<Config extends #{rpc_action_name_pascal}Config> =
          Array<InferResourceResult<#{resource_name}AttributesSchema, Config>>;
        """

      action_type when action_type in [:create, :update] ->
        """
        type Infer#{rpc_action_name_pascal}Result<Config extends #{rpc_action_name_pascal}Config> =
          InferResourceResult<#{resource_name}AttributesSchema, Config>;
        """

      :destroy ->
        """
        type Infer#{rpc_action_name_pascal}Result = void;
        """

      action_type when action_type in [:action, :generic] ->
        # For generic actions, use the returns type if specified
        if action.returns do
          return_type =
            case action.returns do
              {:array, Ash.Type.Struct} ->
                # For struct arrays, assume they return instances of the same resource
                resource_name = resource |> Module.split() |> List.last()
                "Array<#{resource_name}AttributesSchema>"

              _ ->
                ash_type_to_typescript(action.returns)
            end

          """
          type Infer#{rpc_action_name_pascal}Result = #{return_type};
          """
        else
          """
          type Infer#{rpc_action_name_pascal}Result = any;
          """
        end
    end
  end

  defp generate_payload_builder(_rpc_action, action, rpc_action_name) do
    rpc_action_name_pascal = snake_to_pascal_case(rpc_action_name)

    """
    function build#{rpc_action_name_pascal}Payload(
      config: #{rpc_action_name_pascal}Config
    ): Record<string, any> {
      const payload: Record<string, any> = {
        action: "#{action.name}"
      };

      // Add select fields
      if (config.fields) {
        payload.select = config.fields;
      } else {
        payload.select = [];
      }

      // Build load array from load configuration
      if (config.load) {
        payload.load = buildLoadArray(config.load);
      } else {
        payload.load = [];
      }

      // Handle input based on action type
      #{generate_payload_input_handling(action)}

      return payload;
    }
    """
  end

  defp generate_rpc_execution_function(_rpc_action, action, rpc_action_name, endpoint_process) do
    function_name = snake_to_camel_case(rpc_action_name)

    # Add proper type handling for different action types
    is_generic_action = action.type in [:action, :generic]

    rpc_action_name_pascal = snake_to_pascal_case(rpc_action_name)

    result_handling =
      case action.type do
        :destroy ->
          "return;"

        _ when is_generic_action ->
          "return result.data as Infer#{rpc_action_name_pascal}Result;"

        _ ->
          "return result.data as Infer#{rpc_action_name_pascal}Result<Config>;"
      end

    {config_type_param, config_param} =
      case action.type do
        :destroy -> {"", "config: #{rpc_action_name_pascal}Config"}
        _ when is_generic_action -> {"", "config: #{rpc_action_name_pascal}Config"}
        _ -> {"<Config extends #{rpc_action_name_pascal}Config>", "config: Config"}
      end

    result_type =
      case action.type do
        :destroy -> "void"
        _ when is_generic_action -> "Infer#{rpc_action_name_pascal}Result"
        _ -> "Infer#{rpc_action_name_pascal}Result<Config>"
      end

    """
    async function #{function_name}#{config_type_param}(
      #{config_param}
    ): Promise<#{result_type}> {
      const payload = build#{rpc_action_name_pascal}Payload(config);

      const response = await fetch("#{endpoint_process}", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        throw new Error(`RPC call failed: ${response.statusText}`);
      }

      const result = await response.json();
      #{result_handling}
    }
    """
  end

  defp generate_payload_input_handling(action) do
    case action.type do
      :read ->
        """
        if ("filters" in config && config.filters) {
          const filter: Record<string, any> = {};

          for (const [key, value] of Object.entries(config.filters)) {
            if (value !== undefined) {
              filter[key] = value;
            }
          }

          if (Object.keys(filter).length > 0) {
            payload.filter = filter;
          }
        }

        if ("pagination" in config && config.pagination) {
          if (config.pagination.limit !== undefined) {
            payload.limit = config.pagination.limit;
          }
          if (config.pagination.offset !== undefined) {
            payload.offset = config.pagination.offset;
          }
        }

        payload.input = {};
        """

      :create ->
        """
        if ("input" in config) {
          payload.input = config.input;
        } else {
          payload.input = {};
        }
        """

      :update ->
        """
        const updateConfig = config as { id: any; input: any };
        payload.input = { ...updateConfig.input, id: updateConfig.id };
        """

      :destroy ->
        """
        const destroyConfig = config as { id: any };
        payload.input = { id: destroyConfig.id };
        """

      action_type when action_type in [:action, :generic] ->
        """
        if ("input" in config) {
          payload.input = config.input;
        } else {
          payload.input = {};
        }
        """

      _ ->
        """
        payload.input = {};
        """
    end
  end

  defp ash_type_to_typescript(type) do
    case type do
      :string ->
        "string"

      :ci_string ->
        "string"

      :integer ->
        "number"

      :float ->
        "number"

      :decimal ->
        "number"

      :boolean ->
        "boolean"

      :date ->
        "AshDate"

      :time ->
        "string"

      :datetime ->
        "DateTime"

      :utc_datetime ->
        "DateTime"

      :utc_datetime_usec ->
        "DateTime"

      Ash.Type.UtcDatetimeUsec ->
        "DateTime"

      :naive_datetime ->
        "DateTime"

      :uuid ->
        "UUID"

      :atom ->
        "string"

      :map ->
        "Record<string, any>"

      :keyword_list ->
        "Record<string, any>"

      :term ->
        "any"

      {:array, inner_type} ->
        "Array<#{ash_type_to_typescript(inner_type)}>"

      Ash.Type.Term ->
        "any"

      Ash.Type.String ->
        "string"

      Ash.Type.Integer ->
        "number"

      Ash.Type.Boolean ->
        "boolean"

      Ash.Type.Map ->
        "Record<string, any>"

      Ash.Type.Atom ->
        "string"

      Ash.Type.Date ->
        "AshDate"

      Ash.Type.Struct ->
        "Record<string, any>"

      Ash.Type.UtcDatetime ->
        "DateTime"

      Ash.Type.DateTime ->
        "DateTime"

      module when is_atom(module) ->
        # Check if it's an Ash.Type.Enum
        try do
          # First ensure the module is loaded
          Code.ensure_loaded!(module)

          # Check if it has the Ash.Type behaviour and values/0 function
          if function_exported?(module, :values, 0) &&
               function_exported?(module, :cast_input, 2) do
            values = apply(module, :values, [])

            if is_list(values) && Enum.all?(values, &is_atom/1) do
              values
              |> Enum.map(&"\"#{&1}\"")
              |> Enum.join(" | ")
            else
              # Not a proper enum, fallback to module name
              module |> Module.split() |> List.last()
            end
          else
            # For custom types, try to get a simple name
            module |> Module.split() |> List.last()
          end
        rescue
          _ ->
            # If anything fails, fallback to module name
            module |> Module.split() |> List.last()
        end

      _ ->
        "any"
    end
  end

  defp generate_helper_functions do
    """
    // Helper function to build load arrays from load configuration
    function buildLoadArray(loadConfig: any): any[] {
      const result: any[] = [];

      for (const [key, value] of Object.entries(loadConfig)) {
        if (value && typeof value === 'object') {
          const loadItem: any = { [key]: [] };

          if ('fields' in value && value.fields) {
            loadItem[key] = value.fields;
          }

          if ('load' in value && value.load) {
            const nestedLoad = buildLoadArray(value.load);
            if (nestedLoad.length > 0) {
              loadItem[key] = [...(loadItem[key] || []), ...nestedLoad];
            }
          }

          result.push(loadItem);
        } else if (value === true) {
          result.push(key);
        }
      }

      return result;
    }
    """
  end
end
