// This file is auto-generated by AshTypescript. Do not edit manually.

/**
 * Path helper for /auth
 */
export function authPath(): string {
  return "/auth";
}

/**
 * Path helper for /auth/providers/:provider
 */
export function providerPagePath(provider: string): string {
  return `/auth/providers/${provider}`;
}

export type LoginInput = {
  code: string;
  rememberMe?: boolean;
};
/**
 * POST /auth/login
 */
export async function login(input: LoginInput, config?: { headers?: Record<string, string> }): Promise<Response> {
  return fetch("/auth/login", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...config?.headers,
    },
    body: JSON.stringify(input),
  });
}

/**
 * POST /auth/logout
 */
export async function logout(config?: { headers?: Record<string, string> }): Promise<Response> {
  return fetch("/auth/logout", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...config?.headers,
    },
  });
}

export type UpdateProviderInput = {
  enabled: boolean;
  displayName?: string;
};
/**
 * PATCH /auth/providers/:provider
 */
export async function updateProvider(path: { provider: string }, input: UpdateProviderInput, config?: { headers?: Record<string, string> }): Promise<Response> {
  return fetch(`/auth/providers/${path.provider}`, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      ...config?.headers,
    },
    body: JSON.stringify(input),
  });
}

export type EchoParamsInput = {
  name: string;
  count?: number;
  active?: boolean;
};
/**
 * POST /echo
 */
export async function echoParams(input: EchoParamsInput, config?: { headers?: Record<string, string> }): Promise<Response> {
  return fetch("/echo", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...config?.headers,
    },
    body: JSON.stringify(input),
  });
}
