# SPDX-FileCopyrightText: 2025 ash_typescript contributors <https://github.com/ash-project/ash_typescript/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshTypescript.Codegen.ImportResolver do
  @moduledoc """
  Resolves relative import paths between generated TypeScript files
  and generates namespace re-export content.

  Used when generating namespace re-export files that need to import
  from the main generated file, or when any generated file needs to
  import from another.
  """

  @namespace_custom_code_marker "// --- Custom code below this line is preserved on regeneration (do not edit this line) ---"

  @doc """
  The marker comment used to separate generated code from custom code in namespace files.
  Content below this marker is preserved when regenerating namespace files.
  """
  def namespace_custom_code_marker, do: @namespace_custom_code_marker

  @doc """
  Computes a relative TypeScript import path from one file to another.

  Both paths should be relative to the project root (e.g., "assets/js/ash_rpc.ts").
  Returns a relative path suitable for TypeScript `import` statements (without `.ts` extension).

  ## Examples

      iex> resolve_import_path("assets/js/namespace/todos.ts", "assets/js/ash_rpc.ts")
      "../ash_rpc"

      iex> resolve_import_path("assets/js/todos.ts", "assets/js/ash_rpc.ts")
      "./ash_rpc"
  """
  @spec resolve_import_path(String.t(), String.t()) :: String.t()
  def resolve_import_path(from_file, to_file) do
    from_dir = Path.dirname(from_file)
    to_dir = Path.dirname(to_file)
    to_name = Path.basename(to_file, ".ts")

    if from_dir == to_dir do
      "./#{to_name}"
    else
      relative_dir = Path.relative_to(to_dir, from_dir)
      "./#{relative_dir}/#{to_name}"
    end
  end

  @doc """
  Builds import and re-export lines for shared types.

  Generates an `export type * from` re-export, plus a local `import type { ... }`
  for only the type names actually referenced in `body_content`.

  ## Parameters

    * `import_paths` - Map with optional `:types` key containing the import path
    * `shared_type_names` - List of type names exported by the shared types file
    * `body_content` - The generated TypeScript body to scan for type usage
  """
  def build_shared_type_imports(import_paths, shared_type_names, body_content) do
    if import_paths[:types] do
      reexport = "export type * from \"#{import_paths.types}\";"

      used_types = filter_used_types(shared_type_names, body_content)

      if used_types != [] do
        type_list = Enum.join(used_types, ", ")
        local_import = "import type { #{type_list} } from \"#{import_paths.types}\";"
        local_import <> "\n" <> reexport
      else
        reexport
      end
    else
      ""
    end
  end

  @doc """
  Generates a namespace re-export file from a list of categorized exports.

  This is the shared implementation used by both RPC and controller namespace generation.

  ## Parameters

    * `namespace` - The namespace name (used in the header comment)
    * `exports` - List of `{name, kind}` tuples where kind is `:value`, `:type`, or `:zod_value`
    * `namespace_file` - Full path of the namespace file being generated (for import resolution)
    * `main_file_path` - Path to the main source file (RPC or routes)
    * `zod_file_path` - Path to the Zod file (nil to import Zod from main file)
  """
  def generate_namespace_reexport_content(
        namespace,
        exports,
        namespace_file,
        main_file_path,
        zod_file_path
      ) do
    main_import_path = resolve_import_path(namespace_file, main_file_path)

    {zod_exports, non_zod_exports} =
      Enum.split_with(exports, fn {_name, kind} -> kind == :zod_value end)

    {type_exports, value_exports} =
      Enum.split_with(non_zod_exports, fn {_name, kind} -> kind == :type end)

    type_names = type_exports |> Enum.map(fn {name, _} -> name end) |> Enum.sort()
    value_names = value_exports |> Enum.map(fn {name, _} -> name end) |> Enum.sort()
    zod_names = zod_exports |> Enum.map(fn {name, _} -> name end) |> Enum.sort()

    type_export_line =
      if type_names != [] do
        "export type {\n  #{Enum.join(type_names, ",\n  ")}\n} from \"#{main_import_path}\";\n"
      else
        ""
      end

    value_export_line =
      if value_names != [] do
        "export {\n  #{Enum.join(value_names, ",\n  ")}\n} from \"#{main_import_path}\";\n"
      else
        ""
      end

    zod_export_line =
      if zod_names != [] do
        zod_import_path =
          if zod_file_path do
            resolve_import_path(namespace_file, zod_file_path)
          else
            main_import_path
          end

        "export {\n  #{Enum.join(zod_names, ",\n  ")}\n} from \"#{zod_import_path}\";\n"
      else
        ""
      end

    """
    // Generated by AshTypescript - Namespace: #{namespace}
    // WARNING: Do not edit this section - it will be overwritten on regeneration

    #{type_export_line}
    #{value_export_line}
    #{zod_export_line}
    #{@namespace_custom_code_marker}
    """
    |> String.trim()
    |> Kernel.<>("\n")
  end

  defp filter_used_types(type_names, content) do
    type_names
    |> Enum.filter(fn name ->
      Regex.match?(~r/\b#{Regex.escape(name)}\b/, content)
    end)
  end
end
