# SPDX-FileCopyrightText: 2025 ash_typescript contributors <https://github.com/ash-project/ash_typescript/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshTypescript.Codegen.SharedTypesGenerator do
  @moduledoc """
  Generates the shared TypeScript types file (`ash_types.ts`).

  Assembles type aliases, resource schemas, filter types, and utility types
  into a single file that both the RPC and typed controller files import from.
  """

  import AshTypescript.Codegen
  import AshTypescript.Codegen.FilterTypes

  alias AshTypescript.Codegen.UtilityTypes

  @doc """
  Generates the content for the shared types file.

  ## Parameters

    * `opts` - A keyword list with:
      * `:all_resources` - All resources needing schemas (required)
      * `:rpc_resources` - RPC-configured resources (required)
      * `:actions` - RPC actions (required)
      * `:struct_argument_resources` - Resources used as struct arguments (default: [])
      * `:otp_app` - The OTP application name (required)

  ## Returns

  A string containing the TypeScript content for the shared types file.
  """
  def generate(opts) do
    all_resources = Keyword.fetch!(opts, :all_resources)
    rpc_resources = Keyword.fetch!(opts, :rpc_resources)
    actions = Keyword.fetch!(opts, :actions)
    struct_argument_resources = Keyword.get(opts, :struct_argument_resources, [])
    otp_app = Keyword.fetch!(opts, :otp_app)

    custom_imports = generate_custom_imports()

    """
    // Generated by AshTypescript - Shared Types
    // Do not edit this file manually

    #{custom_imports}

    #{generate_ash_type_aliases(rpc_resources, actions, otp_app)}

    #{generate_all_schemas_for_resources(all_resources, all_resources, struct_argument_resources)}

    #{generate_filter_types(all_resources, all_resources)}

    #{UtilityTypes.generate_utility_types()}
    """
  end

  defp generate_custom_imports do
    case Application.get_env(:ash_typescript, :import_into_generated) do
      nil ->
        ""

      imports when is_list(imports) ->
        imports
        |> Enum.map(fn import_config ->
          import_name = Map.get(import_config, :import_name)
          file_path = Map.get(import_config, :file)

          if import_name && file_path do
            "import * as #{import_name} from \"#{file_path}\";"
          else
            ""
          end
        end)
        |> Enum.reject(&(&1 == ""))
        |> Enum.join("\n")

      _ ->
        ""
    end
  end
end
