# SPDX-FileCopyrightText: 2025 ash_typescript contributors <https://github.com/ash-project/ash_typescript/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshTypescript.Codegen.SharedValibotGenerator do
  @moduledoc """
  Generates the shared Valibot validation schemas file (`ash_valibot.ts`).

  Assembles all Valibot schemas into a single dedicated file:
  - Resource-level Valibot schemas (embedded resources, struct arguments)
  - Per-action RPC Valibot schemas
  - Per-route controller Valibot schemas
  """

  alias AshTypescript.Codegen.{ImportResolver, ValibotSchemaGenerator}

  @doc """
  Generates the content for the shared Valibot schemas file.

  ## Parameters

    * `opts` - A keyword list with:
      * `:valibot_resources` - Resources needing Valibot schemas (required)
      * `:types_output_file` - Path to the shared types file (required)
      * `:valibot_output_file` - Path to this Valibot file (required, for import resolution)
      * `:additional_valibot_schemas` - Pre-rendered Valibot schema strings to append (optional)

  ## Returns

  A string containing the TypeScript content for the shared Valibot file.
  """
  def generate(opts) do
    valibot_resources = Keyword.fetch!(opts, :valibot_resources)
    types_output_file = Keyword.fetch!(opts, :types_output_file)
    valibot_output_file = Keyword.fetch!(opts, :valibot_output_file)
    additional_valibot_schemas = Keyword.get(opts, :additional_valibot_schemas, [])

    valibot_path = AshTypescript.Rpc.valibot_import_path()
    types_import_path = ImportResolver.resolve_import_path(valibot_output_file, types_output_file)

    # Resource-level schemas come first (topologically sorted) since per-action/per-route schemas reference them
    resource_valibot_schemas = ValibotSchemaGenerator.generate_valibot_schemas_for_resources(valibot_resources)

    # Collect type names exported from the types file that the Valibot schemas reference
    type_imports = collect_type_imports(resource_valibot_schemas)

    type_import_line =
      if type_imports != [] do
        "import type { #{Enum.join(type_imports, ", ")} } from \"#{types_import_path}\";\n"
      else
        ""
      end

    additional_section =
      additional_valibot_schemas
      |> Enum.reject(&(&1 == ""))
      |> Enum.join("\n")

    """
    // Generated by AshTypescript - Shared Valibot Schemas
    // Do not edit this file manually

    import * as v from "#{valibot_path}";
    #{type_import_line}
    #{resource_valibot_schemas}

    #{additional_section}
    """
  end

  # Extracts type references from Valibot schema code that need to be imported from the types file.
  defp collect_type_imports(_valibot_schemas) do
    # For now, Valibot schemas are self-contained and don't reference types from ash_types.ts.
    []
  end
end
