# SPDX-FileCopyrightText: 2025 ash_typescript contributors <https://github.com/ash-project/ash_typescript/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshTypescript.Codegen.SharedZodGenerator do
  @moduledoc """
  Generates the shared Zod validation schemas file (`ash_zod.ts`).

  Assembles all Zod schemas into a single dedicated file:
  - Resource-level Zod schemas (embedded resources, struct arguments)
  - Per-action RPC Zod schemas
  - Per-route controller Zod schemas
  """

  alias AshTypescript.Codegen.{ImportResolver, ZodSchemaGenerator}

  @doc """
  Generates the content for the shared Zod schemas file.

  ## Parameters

    * `opts` - A keyword list with:
      * `:zod_resources` - Resources needing Zod schemas (required)
      * `:types_output_file` - Path to the shared types file (required)
      * `:zod_output_file` - Path to this Zod file (required, for import resolution)
      * `:additional_zod_schemas` - Pre-rendered Zod schema strings to append (optional)

  ## Returns

  A string containing the TypeScript content for the shared Zod file.
  """
  def generate(opts) do
    zod_resources = Keyword.fetch!(opts, :zod_resources)
    types_output_file = Keyword.fetch!(opts, :types_output_file)
    zod_output_file = Keyword.fetch!(opts, :zod_output_file)
    additional_zod_schemas = Keyword.get(opts, :additional_zod_schemas, [])

    zod_path = AshTypescript.Rpc.zod_import_path()
    types_import_path = ImportResolver.resolve_import_path(zod_output_file, types_output_file)

    # Resource-level schemas come first (topologically sorted) since per-action/per-route schemas reference them
    resource_zod_schemas = ZodSchemaGenerator.generate_zod_schemas_for_resources(zod_resources)

    # Collect type names exported from the types file that the Zod schemas reference
    type_imports = collect_type_imports(resource_zod_schemas)

    type_import_line =
      if type_imports != [] do
        "import type { #{Enum.join(type_imports, ", ")} } from \"#{types_import_path}\";\n"
      else
        ""
      end

    additional_section =
      additional_zod_schemas
      |> Enum.reject(&(&1 == ""))
      |> Enum.join("\n")

    """
    // Generated by AshTypescript - Shared Zod Schemas
    // Do not edit this file manually

    import { z } from "#{zod_path}";
    #{type_import_line}
    #{resource_zod_schemas}

    #{additional_section}
    """
  end

  # Extracts type references from Zod schema code that need to be imported from the types file.
  # Looks for patterns like `InputSchema` references in Zod schemas.
  defp collect_type_imports(_zod_schemas) do
    # For now, Zod schemas are self-contained and don't reference types from ash_types.ts.
    # If they start referencing shared types, we'll add import collection here.
    []
  end
end
