# SPDX-FileCopyrightText: 2025 ash_typescript contributors <https://github.com/ash-project/ash_typescript/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshTypescript.Codegen.SharedTypesGenerator do
  @moduledoc """
  Generates the shared TypeScript types file (`ash_types.ts`).

  Assembles type aliases, resource schemas, filter types, and utility types
  into a single file that both the RPC and typed controller files import from.
  """

  import AshTypescript.Codegen
  import AshTypescript.Codegen.FilterTypes

  alias AshTypescript.Codegen.{ImportResolver, UtilityTypes}

  @doc """
  Generates the content for the shared types file.

  ## Parameters

    * `opts` - A keyword list with:
      * `:all_resources` - All resources needing schemas (required)
      * `:rpc_resources` - RPC-configured resources (required)
      * `:struct_argument_resources` - Resources used as struct arguments (default: [])
      * `:types_output_file` - Path to the types output file, for resolving custom import paths (required)

  ## Returns

  A string containing the TypeScript content for the shared types file.
  """
  def generate(opts) do
    all_resources = Keyword.fetch!(opts, :all_resources)
    rpc_resources = Keyword.fetch!(opts, :rpc_resources)
    struct_argument_resources = Keyword.get(opts, :struct_argument_resources, [])
    types_output_file = Keyword.fetch!(opts, :types_output_file)

    custom_imports = generate_custom_imports(types_output_file)

    """
    // Generated by AshTypescript - Shared Types
    // Do not edit this file manually

    #{custom_imports}

    #{generate_ash_type_aliases(rpc_resources)}

    #{generate_all_schemas_for_resources(all_resources, all_resources, struct_argument_resources)}

    #{generate_filter_types(all_resources, all_resources)}

    #{UtilityTypes.generate_utility_types()}
    """
  end

  defp generate_custom_imports(target_output_file) do
    case Application.get_env(:ash_typescript, :import_into_generated) do
      nil ->
        ""

      imports when is_list(imports) ->
        ImportResolver.resolve_custom_imports(target_output_file, imports)

      _ ->
        ""
    end
  end
end
