# SPDX-FileCopyrightText: 2025 ash_typescript contributors <https://github.com/ash-project/ash_typescript/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshTypescript.Codegen.SharedSchemaGenerator do
  @moduledoc """
  Generates a shared validation schema file for any `SchemaFormatter` implementation.

  Assembles all schemas into a single dedicated file:
  - Resource-level schemas (embedded resources, struct arguments)
  - Per-action RPC schemas
  - Per-route controller schemas
  """

  alias AshTypescript.Codegen.ImportResolver

  @doc """
  Generates the content for a shared schema file.

  ## Parameters

    * `formatter` - A module implementing `AshTypescript.Codegen.SchemaFormatter`
    * `opts` - A keyword list with:
      * `:resource_schemas` - Pre-generated resource schema string (required)
      * `:types_output_file` - Path to the shared types file (required)
      * `:schema_output_file` - Path to this schema file (required, for import resolution)
      * `:additional_schemas` - Pre-rendered schema strings to append (optional)

  ## Returns

  A string containing the TypeScript content for the shared schema file.
  """
  def generate(formatter, opts) do
    resource_schemas = Keyword.fetch!(opts, :resource_schemas)
    types_output_file = Keyword.fetch!(opts, :types_output_file)
    schema_output_file = Keyword.fetch!(opts, :schema_output_file)
    additional_schemas = Keyword.get(opts, :additional_schemas, [])

    import_path = formatter.configured_import_path()
    types_import_path = ImportResolver.resolve_import_path(schema_output_file, types_output_file)
    library_name = formatter.library_name()

    type_imports = collect_type_imports(resource_schemas)

    type_import_line =
      if type_imports != [] do
        "import type { #{Enum.join(type_imports, ", ")} } from \"#{types_import_path}\";\n"
      else
        ""
      end

    additional_section =
      additional_schemas
      |> Enum.reject(&(&1 == ""))
      |> Enum.join("\n")

    """
    // Generated by AshTypescript - Shared #{library_name} Schemas
    // Do not edit this file manually

    #{formatter.import_statement(import_path)}
    #{type_import_line}
    #{resource_schemas}

    #{additional_section}
    """
  end

  # Extracts type references from schema code that need to be imported from the types file.
  defp collect_type_imports(_schemas) do
    # For now, schemas are self-contained and don't reference types from ash_types.ts.
    # If they start referencing shared types, we'll add import collection here.
    []
  end
end
